language: php
sudo: false
cache:
  directories:
  - vendor
install:
- composer install
script:
- ./vendor/phpunit/phpunit/phpunit ./tests
notifications:
  email:
    recipients:
      - astronati+fantasyfootballquotationsparser@vendini.com
    on_success: change
    on_failure: always
